ALTER TABLE user_info
ADD COLUMN name VARCHAR(20) DEFAULT NULL COMMENT '姓名',
ADD COLUMN birthday DATE DEFAULT NULL COMMENT '出生年月日',
ADD COLUMN gender TINYINT DEFAULT 1 COMMENT '0-女性，1-男性',
ADD COLUMN last_login DATETIME DEFAULT NULL COMMENT '最后一次登陆时间';
