CREATE TABLE `user_questions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(100) NOT NULL,
  `answer` VARCHAR(100) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
